### PR TITLE
Gurbmeister patch 1

### PR DESCRIPTION
**Pull request by Gurbmeister**
We found a problem with efi booting systems. this should provide the solution for it.

### CODE REVIEW

**Comment by goldyfruit** [comment]
@Gurbmeister thanks for the PR :+1: 
https://forge.puppet.com/modules/jcpunk/efi doens't seem to be maintained anymore, is it the best library to use?

**Comment by Gurbmeister** [comment]
It is the only one I found.
Although it is nothing more than a mere check whether a certain directory
is present or not. Should also be easy enough to implement this
functionality too. Although, this is all new to me, so I don't know whether
it is a 'nice' thing to do instead of using this library.

**Comment by goldyfruit** [comment]
Thanks.

**Comment by Gurbmeister** [comment]
Thank you!

Op do 11 mrt. 2021 om 17:31 schreef Gaëtan Trellu ***@***.***>

**Pull request merged**
