### PR TITLE
Support BootLoaderSpec style configuration

### LINKED ISSUE #47: Support BootLoaderSpec style configuration
In CentOS 8 BLS is used to configure GRUB menuentries: https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault

puppet-grub2 should support this option to be able to configure CentOS 8 GRUB in the standard way.

To implement this a seperate bool parameter in https://github.com/goldyfruit/puppet-grub2/blob/master/manifests/init.pp#L186 is needed which activates the `GRUB_ENABLE_BLSCFG=$value` in https://github.com/goldyfruit/puppet-grub2/blob/master/templates/default_grub.erb

### PR DESCRIPTION
**Pull request by benibr**
This PR adds $enable_blscfg option.

fixes #47

### CODE REVIEW

**Comment by benibr** [comment]
Hi @goldyfruit can you please comment on the failed CI jobs?

The errors 
```
Error: The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
```
and
```
rubygems-update requires Ruby version >= 2.3.0. The current ruby version is 2.1.9.490.
```
doesn't seem to be directly related to my change and I don't know how to proceed.

**Comment by benibr** [comment]
Any chance this getting reviewed? I'd like to know if I can proceed with this feature?

**Comment by goldyfruit** [comment]
@benibr sorry for the delay, I merged an other PR this morning which generates a conflict with your's. Could you please rebase your PR?

Once it's done, I'll merge your PR.

Thanks :+1:

**Comment by goldyfruit** [comment]
> ```
> Error: The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
> ```
Fixed :)

> ```
> rubygems-update requires Ruby version >= 2.3.0. The current ruby version is 2.1.9.490.
> ```
Looking into it.

**Comment by goldyfruit** [comment]
Ok, the CI is fixed.

**Comment by benibr** [comment]
rebased, looks good

**Comment by goldyfruit** [comment]
Thanks :+1:

**Comment by benibr** [comment]
@goldyfruit Thanks for the support :-)

**Pull request merged**
