### PR TITLE
Added Archlinux support

### PR DESCRIPTION
**Pull request by pschichtel**
Quickly added Archlinux support

### CODE REVIEW

**Comment by goldyfruit** [comment]
@pschichtel Good job ! :+1:

**Comment by pschichtel** [comment]
No problem :smile:. When is the next release planned so I can switch back to forge?

**Comment by goldyfruit** [comment]
@pschichtel I'm currently in vacations, I'm back next week so the next release will be certainly next week. :+1:

**Comment by pschichtel** [comment]
That's fine for me. have fun!

**Comment by goldyfruit** [comment]
@pschichtel done !
https://forge.puppet.com/goldyfruit/grub2/changelog

**Pull request merged**
