### PR TITLE
Don't use legacy facts

### PR DESCRIPTION
**Pull request by pschichtel**

### CODE REVIEW

**Comment by goldyfruit** [comment]
Thanks for the PR :+1:

**Comment by pschichtel** [comment]
@goldyfruit that was quick :) this makes the module puppet8 compatible as far as my testing goes.

**Comment by goldyfruit** [comment]
> @goldyfruit that was quick :) this makes the module puppet8 compatible as far as my testing goes.

Version 1.0.15 published on the forge.

https://forge.puppet.com/modules/goldyfruit/grub2/readme

**Comment by pschichtel** [comment]
Thanks a lot, this was a very fast turnaround :)

**Comment by goldyfruit** [comment]
> Thanks a lot, this was a very fast turnaround :)

I was connected so it was easy!

I preparing version 1.0.16 to get a 5.0 quality score on the Forge.

**Comment by goldyfruit** [comment]
1.0.16 released, let me now if you got issues.

Thanks again @pschichtel :+1:

**Pull request merged**
